// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtlNF1s7IVoobgr1fCHYulCHyQ1UapK_M',
    appId: '1:604247382834:android:4ee3896c3fdf431343952b',
    messagingSenderId: '604247382834',
    projectId: 'personal-4a7fe',
    storageBucket: 'personal-4a7fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6hhssR8K42S5iA-nSJE2HB_UguwztqjU',
    appId: '1:604247382834:ios:a917ab3bfca5010143952b',
    messagingSenderId: '604247382834',
    projectId: 'personal-4a7fe',
    storageBucket: 'personal-4a7fe.firebasestorage.app',
    iosBundleId: 'com.ss.tracker',
  );
}
